### PR TITLE
addition of an extension update ticket template

### PR DESCRIPTION
**Pull request by only1chunts**

### CODE REVIEW

**Review by ramonawalls — APPROVED** [review]
I don't see any problems with adding this new template.

**Comment by mslarae13** [comment]
This looks good to me! I just have 1 question about 
"Please note that while the extensions are designed to be as inclusive as possible of terms appropriate to a particular environment or situations, individual users may choose to select any other additional term(s) from any extension for use with their own choice of packages without the need to request an update of the extension itself."

Actually, more of a note, you can't do this in NMDC or any validating interface.

**Comment by only1chunts** [comment]
> Actually, more of a note, you can't do this in NMDC or any validating interface.
IMO - I think thats an issue with the validation interfaces. As long as the extra term is a valid MIxS term it should not cause any combination to be invalid. The less impediment to people wishing to add MORE metadata  than is suggested the better.

**Comment by turbomam** [comment]
This is a great idea, but needs to be rewritten for the new LinkML term attributes. There's no "Value syntax" anymore. I can help with this.

**Review by turbomam — CHANGES_REQUESTED** [review]
This is a great idea, but needs to be rewritten for the new LinkML term attributes. There's no "Value syntax" anymore. I can help with this.

**Comment by cmungall** [comment]
Discussed with @turbomam - it's OK to use MIxS terminology e.g Value syntax

**Comment by turbomam** [comment]
What decision has been made about how tickets. based on these templates, will be routed into the schema? Is there automation for that? If not, who will be doing this work?

**Pull request merged**
