### PR TITLE
add minimal enum descriptions

### PR DESCRIPTION
**Pull request by turbomam**
The [LinkML linter](https://linkml.io/linkml/schemas/linter.html) (which we should all be using on a regular basis) expects enumerations to have `descriptions`, like all other schema elements. This PR adds descriptions that add some context without just repeating the name of the enums with different casing/punctuation for easier reading.

These enum `description`s can be improve over time. Note that the pattern used here (a count and naming of the slots that use the enum) is somewhat redundant in any system that pre-induced the slots.

The code that generated these enum `description`s will also highlight any enums that are not used by any slots, because they could be considered for deletion. There aren't any enums in that state right now.

So one results of this PR is that future linter results will be terser and thus it will be easier to see cases in which a term isn't complete by the default LinkML guidelines.

### CODE REVIEW

**Comment by turbomam** [comment]
The change in mixs.yaml is too large to see.

example:

``` yaml
MoldVisibilityEnum:
    name: MoldVisibilityEnum
    description: 'permissible values, used by 5 terms: ceil_water_mold, door_water_mold,
      shad_dev_water_mold, wall_water_mold, window_water_mold'
    from_schema: https://w3id.org/mixs
    permissible_values:
      no presence of mold visible:
        text: no presence of mold visible
      presence of mold visible:
        text: presence of mold visible
```

**Comment by turbomam** [comment]
I think we should add the document divider `---` to the beginning of `src/mixs/schema/deprecated.yaml`, as suggested by [Unchanged files with check annotations](Unchanged files with check annotations)

We could double check with Sierra, or learn more about where that warning is coming from.

**Comment by mslarae13** [comment]
I did a quick check, and the additions to mixs.yaml looks good..

> I think we should add the document divider `---` to the beginning of `src/mixs/schema/deprecated.yaml`, as suggested by [Unchanged files with check annotations](Unchanged files with check annotations)
> 
> We could double check with Sierra, or learn more about where that warning is coming from.

I am good with that. But should do it in a separate PR & issue. As this one is specifically enum descriptions & that change is totally unrelated. Too much in 1 PR



> Future action: convert these enums **and all of the schema** to terser forms like
> 
> ```
> MoldVisibilityEnum:
>     description: 'permissible values, used by 5 terms: ceil_water_mold, door_water_mold,
>       shad_dev_water_mold, wall_water_mold, window_water_mold'
>     permissible_values:
>       no presence of mold visible:
>       presence of mold visible: {}
> ```
> 
> * remove redundant `name` and `text` keys
> * remove `from_schema` from auto-generation

Good idea, @turbomam . Can we merge this in and make a separate issue for this?

**Review by mslarae13 — APPROVED** [review]

**Comment by turbomam** [comment]
The conflict is due to the fact that we have some permissible values with  `text`s  now and some without

In the spirit of
- https://github.com/GenomicsStandardsConsortium/mixs/issues/862

I am going to remove the `text`s where they are conflict now

**Comment by turbomam** [comment]
Sierra points out that the list of using slots would need to be maintained (which could be done by rerunning src/mixs/schema/mixs.yaml, which generates an all-inclusive YAML file)

There are probably ~ 100 enumerations. Ideally we would add meaningful descriptions, like their provenance.

**Comment by turbomam** [comment]
the code to regenerate this is now in 
- https://github.com/GenomicsStandardsConsortium/mixs/pull/866/files

**Comment by turbomam** [comment]
the output of the description process can now be found as `assets/mixs-schema-formatting-variants/mixs_with_enum_descriptions.yaml`

in

**Comment by turbomam** [comment]
now redundant with
- #871

**Pull request closed without merging**
