### PR TITLE
Term pages should resolve based on ids

### LINKED ISSUE #637: Terms to resolve based on ids
The current deployment of the documentation does not resolve terms based on ids like before. Restore that feature such that the terms resolve based on ids and not their names.

### PR DESCRIPTION
**Pull request by sujaypatil96**
Fixes #637

### CODE REVIEW

**Comment by sujaypatil96** [comment]
Sorry for the preemptive review request. Will open it up for review soon.

**Comment by turbomam** [comment]
please ensure that all elements are resolved by numerical id. Not just terms. It's possible that we will have to add the class ids, especially the combination class ids

**Comment by turbomam** [comment]
https://github.com/GenomicsStandardsConsortium/mixs/blob/a8764b785d2a0f7f7de2359e2cd85642285b0ee2/src/mixs/schema/mixs.yaml#L30325C1-L30335C36

**Comment by turbomam** [comment]
https://github.com/GenomicsStandardsConsortium/mixs/issues/635

**Comment by sujaypatil96** [comment]
Currently, LinkML docgen supports only the resolution of slots/terms by id/slot_uri. To be able to resolve classes (and other LinkML elements like subsets, enums, etc.) by id as well, I can take that upon request and add that feature to the linkml library upstream.

**Comment by sujaypatil96** [comment]
Made an issue to document your [comment](https://github.com/GenomicsStandardsConsortium/mixs/pull/638#issuecomment-1767079272) Mark: https://github.com/linkml/linkml/issues/1672

**Review by turbomam — CHANGES_REQUESTED** [review]
looking forward to the outcome of @sujaypatil96's LinkML issue for supporting class and term id-based page resolution

**Comment by turbomam** [comment]
I support moving forward with this as long as we can keep https://github.com/linkml/linkml/issues/1672 on the fast track

**Pull request merged**
