### PR TITLE
Add Applicable checklists and extensions section into MIxS docs

### PR DESCRIPTION
**Pull request by sujaypatil96**
In this PR we are seeking to add the _Applicable Checklists and Extensions_ section to the term documentation pages (to be able to link from the term back to the checklists and extensions on the main landing page that use them)

For example, the term documentation page for `HACCP_term` will look like this:

Screenshot 2024-03-12 at 4 30 11 PM

### CODE REVIEW

**Comment by sujaypatil96** [comment]
Update have been made based on the dicussion/feedback captured at TWG meeting on 3/5. See notes doc [here](https://docs.google.com/document/d/1HCmKUGFBm4P8dPCXqL_jOuXe02SF5jQ8hPnTlhanm1Q/edit?usp=sharing).

I propose merging this soon since this update has been pending for a while. The longer it is open the more difficult it gets to resolve merge conflicts in forks, etc.

**Comment by sujaypatil96** [comment]
See this feature applied to my fork of the mixs docs live: https://sujaypatil96.github.io/mixs/0001215/

**Review by turbomam — COMMENTED** [review]
great!

**Comment by only1chunts** [comment]
That looks great on the link you gave! thanks.

**Pull request merged**
