### PR TITLE
Replace code block-based issue template with GitHub issue form

### PR DESCRIPTION
**Pull request by jfy133**
I think this might be a bit easier for users to rapidly make the term request, as they can copy and paste into clear blocks, without having to remove the placeholder texts.

I'm happy to convert the other templates as well if you are interested.

### CODE REVIEW

**Review by turbomam — CHANGES_REQUESTED** [review]
Awesome. Thank you. Apologies for the slow reply.

Since MIxS 6.2+ is LinkML based, there isn't any such thing as a "Structured comment name" anymore (etc., etc.). I can help you align the terminology in this template with the new vocabulary of term attributes if you want.

**Comment by jfy133** [comment]
Hi @turbomam - sure!

I'm still on parental leave and today I have to travel, so it will be a bit of time until I could get to this.

Feel free to edit my fork directly and merge if you have permissions, otherwise you can make code suggestions on the PR and I can commit them (something j can do at least from the GitHub app)

**Comment by jfy133** [comment]
@turbomam I've updated based on what @sujaypatil96 linked to in #678. I've moved the 'old names' into the description, and added two new questions for the unit/multivalue entries.

**Comment by turbomam** [comment]
@sujaypatil96 please integrate this into one of your forks so that we can go through the experience of creating an issue based on this new YAML template

**Comment by sujaypatil96** [comment]
@jfy133 it looks like GitHub is complaining about some YAML syntax error in your issue form: https://github.com/jfy133/genomics-standards-consortium-mixs/blob/main/.github/ISSUE_TEMPLATE/TERM-REQUEST.yml

Could you fix that?

**Comment by jfy133** [comment]
Done, sorry about that - uninformative errors took a bit of experimenting.

Please use the GitHub 'view file' functionality to make sure you're happy with everything (e.g. I can't remember if Multivalued was meant to be required or not) etc.

**Comment by only1chunts** [comment]
> Since MIxS 6.2+ is LinkML based, there isn't any such thing as a "Structured comment name" anymore (etc., etc.). I can help you align the terminology in this template with the new vocabulary of term attributes if you want.

Hi @turbomam , I agree that structured comment name is not a LinkML thing, but it is still what we call it in GSC-MIXS, so I think it best that it is shown as such in the template.
@jfy133, I love this new template, thanks for creating it! Please can you revert the "Title" to "Structured Comment Name", thanks.

**Comment by jfy133** [comment]
@only1chunts it's still listed as in the 'description', or would you rather still have it as the 'primary' name?

**Comment by only1chunts** [comment]
> @only1chunts it's still listed as in the 'description', or would you rather still have it as the 'primary' name?
Sorry, I'm not sure I understand your question, but hopefully this will clarify what I meant:
image

**Comment by jfy133** [comment]
To clarify what I mean

280994996-9972f670-a3b3-4300-b799-3e1a28d74652

**Comment by only1chunts** [comment]
OK, So that "previously known as" bit should be removed as well then (its not "previously known as" it is still known as), if you want to add what the appropriate LinkML word is for it there instead then that could be done (I guess in LinkML its called "title" is it? which sounds rather mis-leading to me as its not a title at all, its really just an alternative name that was created entirely for the INSDC because they auto truncate names longer than 20char)

**Comment by jfy133** [comment]
Ah ok fair enough.

I was just following the request above to follow the table from the Tech group meeting back in June.

I think it's best if you and, Sujay, Mark discuss it and edit the  PR (as it's just terminology now I guess), as I have no opinion either way, and then merge when you have a consensus :)

**Comment by turbomam** [comment]
Thanks for the great discussion guys

@only1chunts what is the requirement for continuing to use language like "Structured comment name"? Or heavens forbid "Expected value"? Those terms aren't defined anywhere in the schema. I don't think they are even defined anywhere in the whole MIxS repo. Where are they defined in some actionable way?

This repo will be harder for everyone to understand if we use terminology that isn't tightly coupled with the repo artifacts. If someone wants to look through the schema to see examples of existing "Structured comment names", how would they do that?

We had an [_agreement_ about mappings between the old nomenclature and the new LinkML-biased nomenclature](https://docs.google.com/document/d/1LzNvt3b09JSNxlf2e2IBwzc33AXe9-mc1GHUR0iBIhg/edit#bookmark=id.gipej8ej40qs), although I will admit that we _didn't agree to retire_ the legacy MIxS nomenclature.

I think a form with a header called `name` and a hint "previously called Structured comment name" is the ideal bridge between theses two nomenclature systems.

**Comment by only1chunts** [comment]
the issue here was that it was proposed that "structured comment name" would be called "Title", which is not something that has been proposed before, but as you suggest and as the document you point to suggests, changing "structured comment name" to "name" is acceptable and should not confuse anyone. But it does mean the template layout needs to be corrected in the wording to ensure consistent use of the mapped terminology.

**Comment by only1chunts** [comment]
I dont know how to go about suggesting changes to the file here, so as its just one small file I've copied and pasted it here with my suggested changes:

```
name: New Term Request
description: "For us to assess a new term request we require the following details:"
title: "New term proposal: "
labels: [NewTerm]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Please make sure you check all these items before submitting your feature request.
      options:
        - label: I have reviewed the existing MIxS checklists and extensions that the term does not exist.
          required: true
  - type: input
    attributes:
      label: Title
      description: >
        The name of the term, previousy known as Package item name or Label
    validations:
      required: true
  - type: input
    attributes:
      label: Name
      description: >
        A version of the name with less than 20 characters and no spaces. Previously known as Structured comment name.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: >
        A clear and concise definition of the term
    validations:
      required: true
  - type: input
    attributes:
      label: Expected value
      description: >
        A short description of the expected pattern or value range of information the term will hold, e.g. text or EFO and/or OBI
      placeholder: >
        "e.g., text or EFO and/or OBI etc...".
    validations:
      required: true
  - type: input
    attributes:
      label: Value syntax
      description: >
        The pattern of the value that the term will be checked against
      placeholder: >
        "e.g. {float} {unit}|{termLabel} {[termID]}|{text}|{timestamp} etc...".
    validations:
      required: true
  - type: input
    attributes:
      label: Example
      description: >
        Please provide a valid example value.
    validations:
      required: true
  - type: input
    attributes:
      label: Preferred unit
      description: >
        Indicate the preferred unit of measurement if appropriate
      placeholder: >
        "e.g, millliter, gram, milligram, liter".
    validations:
      required: false
  - type: input
    attributes:
      label: Extensions(s)
      description: >
        List any extensions that should include the new term
    validations:
      required: false

```

**Comment by jfy133** [comment]
From my phone so can't send screenshot but to make suggestion detailed instructions are as follows

- go to files tab on this PR
- scroll to the line you want to change
- hover over the line to the left hand side of the file pane (near or on the line number itself
- a blue plus button should appear, press it
- this will open a comment box
- in the comment box, in the editor tool bar, there should be a symbol like a +- stacked on top of each other, press that
- a markdown code block should appear with the contents of the line
- edit the code block to how you want the line to be
- once happy, press the 'add single comment' button, or if you make Multiple line edits, press the green 'start a review'

**Comment by mslarae13** [comment]
@only1chunts , @jfy133 , @turbomam 
I think this has been pretty much resolved? I do see some changes from @only1chunts but it's hard to resolved them without just total replacement. An alternative option @only1chunts would be to use the "suggest changes" tool..

See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/commenting-on-a-pull-request#adding-comments-to-a-pull-request:~:text=Optionally%2C%20to%20suggest%20a%20specific%20change%20to%20the%20line%20or%20lines%2C%20click%20%2C%20then%20edit%20the%20text%20within%20the%20suggestion%20block.

Or:

1. On the "Files changed" tab of the PR page, locate the line you want to suggest changes to, then:
2. Hover over that line and click the blue "+" icon that appears
3. Click the "+/- file" icon, which will inject a suggestion block into the comment (see first screenshot)
4. Make changes within the suggestion block
5. Optionally, preview the "Suggested change" (see second screenshot) and add regular commentary outside of the suggestion block
6. Submit the comment (by clicking either "Add single comment" or "Start a review")

**Comment by jfy133** [comment]
@mslarae13 @only1chunts I don't mind either way, but a decision needs to be made on the naming/terms, should this be added to the CIG meeting agenda maybe? I guess it might be a critical interface so a wider round of feedback would help speed this up...

**Comment by lschriml** [comment]
Let’s discuss at GSC24 CIGSent from my iPhoneOn Aug 1, 2024, at 9:56 AM, James A. Fellows Yates ***@***.***> wrote:﻿
@mslarae13 @only1chunts I don't mind either way, but a decision needs to be made on the naming/terms, should this be added to the CIG meeting agenda maybe? I guess it might be a critical interface so a wider round of feedback would help speed this up...

**Comment by jfy133** [comment]
Ok, I won't be able to make it online either it seems, but if someone comes back with a decision either they can directly update the PR or if they give me a list I can make the requested changes :)

**Pull request closed without merging**
