### PR TITLE
diff reports in generated

### PR DESCRIPTION
**Pull request by turbomam**
for issue #413

requires csvdiff from https://aswinkarthik.github.io/csvdiff/

makefile rule `alldiffs` puts reports in directory `generated/`

### CODE REVIEW

**Comment by ramonawalls** [comment]
@turbomam I just resolved a bunch of conflicts when I merged PR #412. Most of them were updating dependency versions, but there were a few other small changes. I'm not sure, but it looks like the conflicts in this branch might revert some of the ones I just change. Can you please confirm that if I resolve these current conflicts to what is in this branch that those are the changes you want?

**Comment by turbomam** [comment]
OK, I will merge main back into whatever I'm working on and get back to you. 

Regarding `poetry.lock`, we can just run `poetry update` before each commit. 

I'll have to check @sujaypatil96's most recent RP  regarding `pyproject.toml`

A lot of my work is taking place in the Makefile, we should be sure not to nuke any of that unless it's intentional

**Comment by turbomam** [comment]
removing the following from `pyproject.toml`. I thought about using them for some text mining but that's experimental and probably shouldn't go in main yet.

- textmining = "^1.0"
- scikit-learn = "^1.0.2"

**Comment by turbomam** [comment]
We should be sure that none of the old gen-markdown stuff gets added back to @sujaypatil96's latest gen-docs commits

Also, we should still run the gen-docs creation and publish it to GH pages

**Comment by turbomam** [comment]
no more merge conflicts

**Review by ramonawalls — APPROVED** [review]

**Pull request merged**
